try {
    a
} catch (e) {
    console.log('Err ' + e);
}

try {
    a
} catch(e) {

}
console.log('b')